### ISSUE TITLE
Reduce the Number of VPNs spanned between Seed- and Shoot cluster

### ISSUE THREAD

**Issue by marwinski** [gardener/vpn#26]
# Story

As an operator I want to save costs on running the Gardener infrastructure. 

# Motivation 

Currently each pod in the control plane (currently the kube-apiserver and prometheus) need their own vpn endpoint located in the pod. With additional pods that need access we span even more VPNs which does not appear to be ideal.

# Acceptance Criteria

- There is one VPN endpoint in the shoot cluster and one in the seed cluster control plane for a cluster.
- There is a standalone integration test for the new implementation

# Implementation Proposal

There shall be one VPN endpoint pod in the seed cluster and one endpoint pod in the shoot cluster. For security reasons it appears preferable if the shoot cluster VPN pod initiates the VPN connection to the seed cluster VPN (today it is vice versa). This way the shoot cluster VPN endpoint could receive its configuration automatically. 

This would require some additional configuration for the control plane in the seed cluster and the kube-apiserver and prometheus pods: they will need to add routes to the shoot host network, shoot service network and shoot pod network via the VPN endpoint pod in the seed cluster for example by running the route commands in an init container. 

At the same time the VPN Seed pod will need to have IP Forwarding enabled and would require an SNAT configuration. In addition it shall also have a firewall configuration to deny all traffic coming from the shoot cluster.

**Comment by rfranzke** [comment]
> For security reasons it appears preferable if the shoot cluster VPN pod initiates the VPN connection to the seed cluster VPN (today it is vice versa). 

Today the vpn-seeds connect to a load balancer exposed in the vpn-shoot. Do you really want to expose an endpoint in the Seed to which the vpn-shoot connects to? Doesn't this rather increase the security risks instead of shrinking them?

Other than that I like the approach of running one VPN pod in the Shoot namespace in the Seed to which the components needing connectivity to Shoot networks (pod/service/node) like kube-apiserver/prometheus route.

**Comment by marwinski** [comment]
well, my initial thought was to expose one VPN endpoint per control plane basically just reversing the approach. This is relatively straightforward and I don't see a security issue here (in the end the shoot only has credentials for the correct endpoint. 

That said, it would be much cooler to just have one VPN endpoint in the seed cluster and route all traffic through that - would save us a lot of cost in load balancers and pods. Well it can be done :-) but is quite significantly more complex (need to do some form of tunneling) but nevertheless a worthwhile exercise.

**Comment by vlerenc** [comment]
I guess, what @franzke meant was that every endpoint in the seed cluster is a possible attack vector. This way, we double the seed LBs and double the number of attack vectors (previously only the API server, now API server and VPN).

As for having only one seed cluster LB overall, that would certainly significantly drop the costs, but it would also create new security risks. Then all control planes must reach the same VPN (and can possibly break out) and all traffic would run side-by-side in the same VPN pods (and we must implement auto-scaling, which seems complex).

**Comment by marwinski** [comment]
Well, having all the endpoints (one for each shoot) in the seed cluster is not a risk from my point of view and I consider the current setup much more unsafe. 

Agreed, having only one endpoint is more difficult but I do believe this is also quite possible (need to work with overlays in order to solve the problem of overlapping ip ranges, can (actually must) put a firewall into the vpn endpoint in the shoot which we haven't done so far. So even this I would consider more secure than the current solution.

**Comment by vlerenc** [comment]
Hmm... a lot of effort for the single seed VPN and more security head aches, really? Have you valued all the pros and cons against each other? I am not so certain that the security net gain is at all positive, much less whether it would justify the effort.

**Comment by marwinski** [comment]
We, that means @DockToFuture and myself have done 2 days of thourough investigation. This is the result:

* We did look at providing an endpoint for each shoot cluster in the seed cluster reversing he connection build up and control. This however causes more headache as the shoot cluster endpoint would need to query the seed cluster api server for the endpoint in the cluster. Moving that information into the shoot cluster control plane would require an additional component and we therefor abandoned the approach.

* We have looked into routing the traffic to the kubernetes service through the VPN. @rfranzke  pointed out that there is a hen an egg problem: calico makes use of the service but need to run prior to the vpn service or anything else. We could therefor only route the traffic through the vpn after calico has been initialised (which needs to be first). This would work but could possibly render the cluster unusable if something goes wrong (e.g. node with vpn endpoint going down). Due to the possible maintenance headache we will not pursue this approach.

* We have looked into getting rid of the "push configuration information into the seed cluster vpn endpoint" mechanism. This mechanism is subject to some security concern. This is however also hard to do:

  * the push configuration allows multiple clients (e.g. multiple api servers and prometheus to connect to the shoot cluster endpoint in quite a comfortable way (e.g. link addresses are automatically assigned dynamically, there is no problem when api server disappear and reappear). When we originally designed the solution there was just one single api server and prometheus which we could configure statically. Due to api server scaling this is not possible anymore. 

  * A solution to this is to have one single static vpn connection between the shoot cluster and the seed cluster. This is called the p2p mode in OpenVPN and route all traffic through that VPN. This again, unfortunately is all but simple:

    * the p2p mode only allows one connection. When that connection is established the VPN server does not listen on the assigned port anymore. This goes very badly with load balancers as they almost immediately mark the endpoint as bad and don't forward traffic anymore. When the VPN goes down it can only be re-established once the load balancer has confirmed the port open again (which works as the VPN server is listening again). Shortening this would require special load balancer configurations for each cloud provider. 
A solution to this dilemma would be to attach a tiny proxy at the endpoint that always listens for connections and forward them to the VPN server if no connection does exist. This should also solve issue #35 as no superfluous connections should hit the vpn server anymore. The proxy could be enhanced to detect LB health checks even if we don't implement the proposals in here. 

    * Having one endpoint in the seed cluster means that for each control plane the api servers and prometheus need to direct their traffic through the single VPN pod which is dependent on the namespace. We did believe this to be a simple networking manner but it is not. In a "normal" network you could just add a rule like "route traffic to pod/node/service network through vpn endpoint" but this does not work with the current network spanned by calico. In the sentence above "vpn endpoint" really means a MAC address which calico does not provide so this simple approach does not work.
As a result we have experimented with a tunnel/overlay network between the API servers and the VPN endpoint. This worked however there is another problem: the configuration of the tunnel is static which kind of resembles the problem descried above with the dynamic VPN configuration. That configuration needs to be done in the vpn endpoint pod and the api servers and we need to build it or ...
... use OpenVPN for this (without security). This does provide the dynamic setup and for the connection handling between the api server pods and the vpn endpoint in the seed cluster. 

* We have looked at getting rid of the load balancers and provide special machines with public IP addresses only for the VPN in the clusters as load balancers are of some concern for the VPN connections (at least on AWS small machines are even cheaper than load balancer). From a security point of view this is of no additional concern to me as it does not matter whether a hole is opened though a load balancer or an open port of a single machine. The latter actually only opens a hole on one machine where the load balancer opens a hole on all machines. 
We do see two general problems with load balancers across all infrastructures:
  * load balancers randomly distribute the vpn connection to one of the cluster nodes - in most cases the connection will go to a node which does not host the VPN endpoint so this connection needs to be forwarded. This generates additional traffic and will make the connection more unstable should that node go down, be updated or be recycled. In fact, a rolling update could lead to many disruptions of the VPN connection (not just one). 
  * load balancers have the tendency to interrupt the connection from time to time. We have seen several cases on OpenStack and AWS where a connection was not possible for hours at a time. Unfortunately this does not appear to be reproducible.
  * it would be preferable to use UDP for the VPN but most load balancers don't seem to support it.
Adding machines and adding a pubic IP address would require cloud specific coding and be significant effort. 

  Although the preferable approach from my point of view we currently don't consider the problems with the load balancer significant enough to go for this approach. There is relatively little traffic going through the VPN so detours through other hosts as well as tunneling IP over TCP is of little concern. 

So where does this leave us: 

We should build that little tcp proxy and place it in front of the VPN endpoint. This could handle the load balancer health checks and get rid of all the garbage in the log files. This should be little effort but probably needs 2 iterations until stable for all cloud providers. 

Apart from that we need to chose whether we leave everything else "as is" and accept the security risk or go with the single point to point connection. As we cannot judge the risk of the current approach (it is probably very low to non-existent) we should nevertheless go for the "safer" approach using the single p2p connection.

**Comment by rfranzke** [comment]
> We did look at providing an endpoint for each shoot cluster in the seed cluster reversing he connection build up and control. This however causes more headache as the shoot cluster endpoint would need to query the seed cluster api server for the endpoint in the cluster. Moving that information into the shoot cluster control plane would require an additional component and we therefor abandoned the approach.

Apart from the security concerns (don't you have any?): Why can't you let Gardener inject the endpoint into the deployment of the vpn-shoot component during deployment? What is the reason for the need to query the seed cluster api server?

> We have looked into routing the traffic to the kubernetes service through the VPN. @rfranzke pointed out that there is a hen an egg problem: calico makes use of the service but need to run prior to the vpn service or anything else. We could therefor only route the traffic through the vpn after calico has been initialised (which needs to be first). This would work but could possibly render the cluster unusable if something goes wrong (e.g. node with vpn endpoint going down). Due to the possible maintenance headache we will not pursue this approach.

Well, we run the vpn-shoot as a normal pod. What we could also do is running it as in the host network. Then it is not depending on calico and would be scheduled and started also without network. Maybe this also helps with the sporadic VPN issues we are seeing. WDYT?

> We have looked into getting rid of the "push configuration information into the seed cluster vpn endpoint" mechanism. This mechanism is subject to some security concern. This is however also hard to do:

Same as above: Can't we simply go to where we were before and get rid of pushing information? Instead, we could statically configure vpn-shoot during deployment time. As far as I know the routing information does not change dynamically, right?

> load balancers randomly distribute the vpn connection to one of the cluster nodes - in most cases the connection will go to a node which does not host the VPN endpoint so this connection needs to be forwarded. This generates additional traffic and will make the connection more unstable should that node go down, be updated or be recycled. In fact, a rolling update could lead to many disruptions of the VPN connection (not just one).

Does the `.spec.externalTrafficPolicy` field in the [`ServiceSpec`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#servicespec-v1-core) help here?

**Comment by marwinski** [comment]
>> We did look at providing an endpoint for each shoot cluster in the seed cluster reversing he connection build up and control. This however causes more headache as the shoot cluster endpoint would need to query the seed cluster api server for the endpoint in the cluster. Moving that information into the shoot cluster control plane would require an additional component and we therefor abandoned the approach.

>Apart from the security concerns (don't you have any?): Why can't you let Gardener inject the endpoint into the deployment of the vpn-shoot component during deployment? What is the reason for the need to query the seed cluster api server?

Yes that would be an option - but keep in mind that you need to do that all the time anything changes in the seed. Do we really need that effort? 

>> We have looked into routing the traffic to the kubernetes service through the VPN. @rfranzke pointed out that there is a hen an egg problem: calico makes use of the service but need to run prior to the vpn service or anything else. We could therefor only route the traffic through the vpn after calico has been initialised (which needs to be first). This would work but could possibly render the cluster unusable if something goes wrong (e.g. node with vpn endpoint going down). Due to the possible maintenance headache we will not pursue this approach.

> Well, we run the vpn-shoot as a normal pod. What we could also do is running it as in the host network. Then it is not depending on calico and would be scheduled and started also without network. Maybe this also helps with the sporadic VPN issues we are seeing. WDYT?

Didn't you say that nothing is scheduled until the network is ready? If not, running the vpn-shoot on the host network is certainly an option.

>> We have looked into getting rid of the "push configuration information into the seed cluster vpn endpoint" mechanism. This mechanism is subject to some security concern. This is however also hard to do:

> Same as above: Can't we simply go to where we were before and get rid of pushing information? Instead, we could statically configure vpn-shoot during deployment time. As far as I know the routing information does not change dynamically, right?

Keep in mind that you must configure both sides, e.g. when you add an API server you need to configure the vpn-shoot endpoint as well. It is not just about having a configuration in the VPN-seed. Do you really want that coding in Gardener? 

>> load balancers randomly distribute the vpn connection to one of the cluster nodes - in most cases the connection will go to a node which does not host the VPN endpoint so this connection needs to be forwarded. This generates additional traffic and will make the connection more unstable should that node go down, be updated or be recycled. In fact, a rolling update could lead to many disruptions of the VPN connection (not just one).

> Does the .spec.externalTrafficPolicy field in the ServiceSpec help here?

Probably, we will test that, but that said, this will probably lead to delays of several minutes when something breaks an the pod is re-scheduled.

**Comment by rfranzke** [comment]
>>> We did look at providing an endpoint for each shoot cluster in the seed cluster reversing he connection build up and control. This however causes more headache as the shoot cluster endpoint would need to query the seed cluster api server for the endpoint in the cluster. Moving that information into the shoot cluster control plane would require an additional component and we therefor abandoned the approach.

>>Apart from the security concerns (don't you have any?): Why can't you let Gardener inject the endpoint into the deployment of the vpn-shoot component during deployment? What is the reason for the need to query the seed cluster api server?

>Yes that would be an option - but keep in mind that you need to do that all the time anything changes in the seed. Do we really need that effort? 

What can change? We are only talking about https://github.com/gardener/vpn/blob/master/shoot/openvpn.config.template#L30-L32 right? If so: The CIDRs cannot change - what about the network masks? Must they be different for each vpn-seed when having multiple API servers? I guess no, right? We already have multiple vpn-seeds right now and I don't see any special computation here: https://github.com/gardener/vpn/blob/master/shoot/network-connection.sh#L27-L56

>>> We have looked into routing the traffic to the kubernetes service through the VPN. @rfranzke pointed out that there is a hen an egg problem: calico makes use of the service but need to run prior to the vpn service or anything else. We could therefor only route the traffic through the vpn after calico has been initialised (which needs to be first). This would work but could possibly render the cluster unusable if something goes wrong (e.g. node with vpn endpoint going down). Due to the possible maintenance headache we will not pursue this approach.

>> Well, we run the vpn-shoot as a normal pod. What we could also do is running it as in the host network. Then it is not depending on calico and would be scheduled and started also without network. Maybe this also helps with the sporadic VPN issues we are seeing. WDYT?

>Didn't you say that nothing is scheduled until the network is ready? If not, running the vpn-shoot on the host network is certainly an option.

I said normal pods are not scheduled until the network is ready. We are running the vpn-shoot as normal pod. However, pods inside the host network will certainly be scheduled and started (how should calico start itself otherwise?). I didn't think about this yesterday when we were talking about it because I wasn't considering that we might want to run vpn-shoot in the host network but just as a normal pod.

>>> We have looked into getting rid of the "push configuration information into the seed cluster vpn endpoint" mechanism. This mechanism is subject to some security concern. This is however also hard to do:

>> Same as above: Can't we simply go to where we were before and get rid of pushing information? Instead, we could statically configure vpn-shoot during deployment time. As far as I know the routing information does not change dynamically, right?

>Keep in mind that you must configure both sides, e.g. when you add an API server you need to configure the vpn-shoot endpoint as well. It is not just about having a configuration in the VPN-seed. Do you really want that coding in Gardener? 

See above, depends on whether the network masks can be the same for multiple API server replicas. If yes, I don't see any problem coding that in Gardener. It was the same before switching to OpenVPN. Do I miss something?

>>> load balancers randomly distribute the vpn connection to one of the cluster nodes - in most cases the connection will go to a node which does not host the VPN endpoint so this connection needs to be forwarded. This generates additional traffic and will make the connection more unstable should that node go down, be updated or be recycled. In fact, a rolling update could lead to many disruptions of the VPN connection (not just one).

>> Does the .spec.externalTrafficPolicy field in the ServiceSpec help here?

>Probably, we will test that, but that said, this will probably lead to delays of several minutes when something breaks an the pod is re-scheduled. 

Several minutes, why?

**Comment by vlerenc** [comment]
I guess we can close this one as VPN is being changed completely.
