### ISSUE TITLE
Unstable Connections

### ISSUE THREAD

**Issue by vlerenc** [gardener/vpn#34]
VPN reconnects again and again across all infrastructures (looks good with ”TCP connection established” and then flaps to “Connection reset, restarting” for no apparent reason).

**Comment by vlerenc** [comment]
From Dirk:

We have looked at the VPN behaviour on all he cloud providers and these are some initial findings:
 
It appears that there is generally no problem with the VPN on GCP, and OpenStack. There are too few clusters on Azure to tell but the logs that we have indicate that this is in line with GCP and OpenStack …
 
The problem that we saw on OpenStack went away last Friday roughly at 11:36. We did not see a glitch afterwards. The OpenStack guys are at a loss to explain this.
 
In general we do see some connection resets from the load balancers (less than one per day). This is however not problematic from my point of view and kind of works as designed as LB are “allowed” and known to do this.
 
The story is quite different on AWS:
 
We do see lots of instances where the load balancer kills the connection after connection establishment or immediately after the creation of the tunnel, or shortly thereafter (in a flapping manner which can go on for hours). This appears to be an issue with the AWS ELB. On the other hand we see instances that are stable for more than one day.
 
In addition there are VPN outages due to the IP address change of the load balancers. From the logs we cannot judge how long the interruption is (could be 30 seconds but also 15 minutes).
 
We have seen the same behaviour in our test sandbox on AWS. As a consequence I (Dirk) would recommend not to use ELBs on AWS.
 
Next steps:
 
We are currently checking whether the Network Load Balancer (NLB) behaves any different. If so this might be a viable option.

**Comment by marwinski** [comment]
Some first results of the VPN test on AWS. The VPN connections are running between 5 and 6 days:

- Direct connection via an elastic IP address: no interruption
- Connection via a classic load balancer (the one we use with Gardener): one interruption due to the load balancer
- Connection via the network load balancer: no interruption

**Comment by vlerenc** [comment]
Sounds good, thank you.

Not sure whether CLBs really have an issue (statistically hard to tell from a sample set of 1), but we were considering NLBs anyway also for modernity and cost reasons (see gardener/gardener#242).

The change should be minimal, so why not doing it for VPN?
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

**Comment by marwinski** [comment]
We do suspect another class of problems with load balancers that we have seen on Azure yesterday:

There was an event on a development cluster (hard to tell but probably a restart of the single worker node) which led to the VPN being unavailable for roughly 10 minutes. One suspicion is that the health check did take some time to learn that the VPN server was available again. 

From those kind of failures it is apparent that we probably need to invest a lot into each infrastructure to tweak the load balancer into doing the "right" thing... We @DockToFuture and myself have therfore decided to invest a little bit more into alternative approaches. LBs are not right for doing this and problems might never end ...

**Comment by vlerenc** [comment]
Please wait @marwinski @DockToFuture, that doesn't sound reasonable. Why did we go for LBs in the first place? Obviously, because they are a key feature of Kubernetes, we reuse as much as possible from the Kubernetes stack/functionality without reimplementing anything, we have limited time.

If Azure takes 10 minutes to get their LBs working again after a listener dropped/a new one joined, then this is Azure's problem, not ours. Every other application/service running there will have the same problem, so Azure it incentivised enough to improve their behaviour.

Plus, Azure is not in the same league as AWS and GCP or OpenStack. We know of the many performance problems Azure has (after all, bringing up clusters takes 2-4 times longer on Azure than anywhere else) and the sporadic outages. There is nothing we can do about and it should certainly not drive us to throw away everything if the LBs respond fast everywhere else.

I don't say, we can't reimplement it, but the reasoning must be right. Just because Azure has a problem with a standard Kubernetes feature that the VPN like all apps/services need to have/work properly is not a good reason.

Please reconsider, especially because you wrote above, that everything looked stable in your experiment. Can you repeat it with more clusters/VPNs. What about the NLB? That should be a minimal change, right?

Look, all I am saying is that LBs have to work - whether we use them for VPN or not. Unless we don't find a specific problem with OpenVPN and LBs, there is no good reason to drop LBs just if one infrastructure has issues with them.

**Comment by marwinski** [comment]
Well, we do observe similar problems on GCP- it is not just the behaviour on Azure. **LBs are just not right for doing single connection VPNs.** We have to tweak them for each cloud provider and we will continuously see issues and need to re-tweak. This is not what I would consider getting it done once and for all.

I myself was trying to refrain from doing it again, however all of that fuzzy behaviour changed my opinion - together with the belief that doing it "right" is not that hard - we do have the building blocks.

**Comment by vlerenc** [comment]
@marwinski @zanetworker @DockToFuture @mvladev Please forgive brevity while grooming the backlog. Issue still relevant in the context of the new VPN solution or would you like to close it (it is rotten)?

**Comment by zanetworker** [comment]
I don't see this issue happening even with the old VPN solution, so I would say we close it. That said, the new solution is still under experimentation till now (bugs upstream being fixed, and is being enabled / disabled to test) and would only work for >=1.18 clusters.
