### ISSUE TITLE
Confusing Logs

### ISSUE THREAD

**Issue by vlerenc** [gardener/vpn#35]
VPN shoot logs contains many connection termination messages, which are related to the LB health checks and which confuse the users in believing there is an issue and make the analysis harder for the ops, so is there a way to filter out the health check related (expected) log message?

**Comment by marwinski** [comment]
I agree that the logs are quite useless and are getting huge but filtering this out will most likely filter too much. We can increase the health check timeouts (not sure whether we can add that cloud provider specific meta-data to lb services to do that to reduce the number of connection attempts. 

Another option would be to reduce logging to level 0:

   ``` No output except fatal errors. ```

I have just tried it and the above statement is quite true ... This might be the better option - especially when we make that configurable with level 0 as the default. @vlerenc , @DockToFuture: what do you think?

**Comment by rfranzke** [comment]
> We can increase the health check timeouts (not sure whether we can add that cloud provider specific meta-data to lb services to do that to reduce the number of connection attempts.

I'd refrain from putting more cloud specific code into places where it's not needed in general.

**Comment by vlerenc** [comment]
I can't judge @marwinski, but if it means we don't see the LB health check logs anymore, but would see seed-to-shoot VPN connection termination logs (are they fatal?), that's OK. However, we certainly won't see seed-to-shoot VPN connection established logs anymore either, I guess. Anyway, if that's what we can do, then let's do it. We don't want guessing users confusing ops and we want ops to see at least critical events if we can't get rid of the health check stuff. Thanks!

**Comment by marwinski** [comment]
There is another option to filter the requests from the API server. The log usually looks like this:

```
Fri Oct 19 06:34:30 2018 TCP connection established with [AF_INET]10.250.24.187:57166
Fri Oct 19 06:34:30 2018 10.250.24.187:57166 Connection reset, restarting [0]
Fri Oct 19 06:34:31 2018 TCP connection established with [AF_INET]10.250.24.187:47276
Fri Oct 19 06:34:31 2018 10.250.24.187:47276 Connection reset, restarting [0]
```

With multiple nodes we do see a lot more connections but they are relatively straightforward to filter: just look for connections and if they are closed in the same (or next second) don't print the "established" and "reset" messages

**Comment by marwinski** [comment]
This is only a real problem if the load balancers are "flapping". We only see this on AWS (did we really in the past few weeks?). For AWS we are only looking at this problem again when we have switched to NLBs as from my point of view the CLBs are to blame for this issue. 

As filtering out would remove a lot of potentially useful information I would not do that.

**Comment by vlerenc** [comment]
Closing as VPN will change anyhow.
