### ISSUE TITLE
Issue with VPN Health Check

### ISSUE THREAD

**Issue by marwinski** [gardener/vpn#36]
From time to time we do see a lot of alerts that indicate that the VPN connection is not stable. At first glance the connection appears to be healthy. We have investigated on case and found the following behaviour which went away after a couple of hours:

The VPN test (via blackbox exporter) invokes the the Kubernetes service, e.g. curl `https://100.64.0.1`. This request goes via the VPN to the shoot cluster where the address is re-written by iptables rules to go to the public endpoint of the API server. Although awkward, this must always work. 

What we saw is that a couple of those requests did fail or timeout after pretty much 30 seconds or 1 minute. We were not able to see a pattern but it was reproducible every 2nd or 3rd time. 

A tcpdump on the vpn-shoot pod showed that the SYN packets come in through the VPN but there is not reply (within a couple of seconds for failing connections attempts). We did not probe any other interfaces at that time. 

When running the curl command from within the vpn-shoot pod it did always work, we did not see any connection timeouts here. 

This said, we currently don't see this behaviour. What we can say for sure is that the shoot cluster vpn-shoot pod has not been restarted.

This is merely a reminder for the next time when we see the problem. Initial step should be to get a tcpdump from the pods eth0 interface (port 443 should be sufficient) as well as eth0 from the worker node (can be obtained from calico pod that host host network).

On a cluster with default network configuration the following script should indicate whether we see this problem or not:

```
#!/bin/bash

KUBECONFIG=$1
NAMESPACE=$2
METADATA_IP=$3

apiserver=$(kubectl --kubeconfig=${KUBECONFIG} get pods -n ${NAMESPACE} | grep kube-apiserver | head -n 1 | awk '{print $1}')

kubectl --kubeconfig=${KUBECONFIG} -n ${NAMESPACE} exec -it ${apiserver} -c kube-apiserver -- bash -c "apt-get update && apt-get -y install curl"
kubectl --kubeconfig=${KUBECONFIG} -n ${NAMESPACE} exec -it ${apiserver} -c kube-apiserver -- curl  https://100.64.0.1
````

It is an indication for this particular problem if this takes 30 seconds or more or returns with an error.

**Comment by vlerenc** [comment]
Thanks for the analysis. I suggest to improve the VPN health check, though. Would it be possible to make a simpler port-forward/proxy test @marwinski @DockToFuture @mvladev, just reaching something/anything in the shoot cluster itself (e.g. one of the addons in `kube-system`)? Then we wouldn't include the back channel via the `kubernetes` service/endpoint to the API server(s) through the LBs in the VPN health check (much cleaner), which may fail when AWS changes the API server LB IP or the API servers scale-in/the connection therefor terminates or for other reasons (like was the case with one of our larger users in the past) or the users (D)DoS their own API servers (which we also have seen). The VPN health check should just test VPN and not (much) more. WDYT?

**Comment by marwinski** [comment]
@vlerenc I absolutely agreed and already proposed this to @mvladev. Nevertheless this is something to iron out as it will not go away by its own. So I would suggest to keep the test "as is" because it points us to this kind of problem that we would not see otherwise.

**Comment by vlerenc** [comment]
Then how about having two separate health checks? One that really only checks the VPN (as described above) and one that checks the `kubernetes` service. If the VPN check fails, it suppresses any alerts that depend on VPN such as the `kubernetes` service check and if the other check fails/fires, we know it does that only because of the `kubernetes` service itself and not because of the VPN (the checks would then have appropriate names, helping right away assigning the alert).

As it is right now, it cannot stay, because it's not helpful. Since months nobody cares one iota when (s)he sees VPN down, because it can mean anything and nothing. That's something we should really improve, wouldn't you/all agree? Otherwise this discussion was pointless - some learning must be the consequence of the problems we see, so that we can improve.

**Comment by marwinski** [comment]
@mvladev can you go ahead and separate these tests. We do see lots of issues at the moment only Azure that seems to indicate some deep down hidden issue.

@DockToFuture  can you take this over with help from @mandelsoft and @afritzler. As we had similar issues on other platforms this might be related to the MTU - at least that would be my initial feeble guess.

**Comment by DockToFuture** [comment]
The problems still persist even with a smaller MTU size (1450,1400).

**Comment by marwinski** [comment]
I have run curl https://100.64.0.1 in the vpn-seed pod serveral times in a row. This is the result:

````
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* connect to 100.64.0.1 port 443 failed: Operation timed out
* Failed to connect to 100.64.0.1 port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 100.64.0.1 port 443: Operation timed out

real	2m8.616s
user	0m0.005s
sys	0m0.004s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	0m0.098s
user	0m0.016s
sys	0m0.001s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* connect to 100.64.0.1 port 443 failed: Operation timed out
* Failed to connect to 100.64.0.1 port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 100.64.0.1 port 443: Operation timed out

real	2m11.482s
user	0m0.007s
sys	0m0.002s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	0m32.081s
user	0m0.016s
sys	0m0.002s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	0m0.055s
user	0m0.011s
sys	0m0.006s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	0m0.055s
user	0m0.015s
sys	0m0.002s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	0m0.099s
user	0m0.015s
sys	0m0.002s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* connect to 100.64.0.1 port 443 failed: Operation timed out
* Failed to connect to 100.64.0.1 port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 100.64.0.1 port 443: Operation timed out

real	2m12.056s
user	0m0.006s
sys	0m0.003s
bash-4.4# time curl -v https://100.64.0.1
* Rebuilt URL to: https://100.64.0.1/
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

real	1m4.014s
user	0m0.012s
sys	0m0.008s
bash-4.4#
````

This makes
- 3 failed attempts
- 4 successful attempts
- 1 successful after 32s
- 1 successful after 64a

**Comment by marwinski** [comment]
The root cause for this appears to be packet loss on the server side (between load balancer and kube api server) due to aggressive re-use of ports.

We are further evaluating this but at this time we are sure this is not a problem related to the VPN.

**Comment by marwinski** [comment]
Issue is caused by a combination of aggressive port re-use by the Azure gateway and a small bug in kubernetes. Filed https://github.com/kubernetes/kubernetes/pull/72879 to fix kube-proxy.

**Comment by vlerenc** [comment]
CC @juergenschneider as you were asking for Azure issues (see @marwinski comment above).

**Comment by vlerenc** [comment]
@marwinski  @zanetworker @DockToFuture @mvladev Please forgive brevity while grooming the backlog. Issue still relevant in the context of the new VPN solution or would you like to close it (it is rotten)?

**Comment by zanetworker** [comment]
this seems to have been an underlying infrastructure issue, so I will close it for now since its irrelevant to the VPN health-checks.
