### ISSUE TITLE
Dedicated internal IP range for master to nodes communication

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/vpn#52]
0.0.0.0/0 currently is the source IP range for VPN connectivity which is considered to be a security risk. Reduce the attack surface by specifying a dedicated internal IP range for master to nodes communication (via kublet).

**Comment by rfranzke** [comment]
Why is this a security risk? Can you elaborate on how ingress to the VPN is different from ingress to the shoot's API server?

**Comment by ThormaehlenFred** [comment]
From my point of view in case of VPN we know the source. With shoot's API server we don't.

**Comment by rfranzke** [comment]
I don't understand this argument. You have to secure the endpoints anyways. As you say, for the API server we can't start to whitelist any IPs. Why should we do it for the VPN? This would not only make the configuration of the Gardener system way more complex, it would also introduce a new complexity wrt control plane migration. If there is no better argument for the necessity of introducing whitelisting I would refrain from implementing it, tbh.

**Comment by vlerenc** [comment]
In addition, we still hope to eliminate this security group anyways with the work @mvladev has explored/started in https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md that will also include the VPN. Still, it would only turn around the complexity and the main question is actually whether IP whitelisting is beneficial in any meaningful way. In the end, we would have to register the IP pool of the hyperscaler or go to even greater lengths and do that specifically per NAT GW, etc. which would drive complexity as @rfranzke already said.

**Comment by mvladev** [comment]
IP-based security simply won't work - even on private OpenStack installations you might have multiple NATs along the path and no way to preserve the source IP address.

Even the UK government have given up on such firewalls. https://technology.blog.gov.uk/2017/01/03/a-whitelisting-approach-for-cloud-apis/

**Comment by vlerenc** [comment]
I guess we can delete this one since we anyways move the VPN LB into the seed.

/cc @ThormaehlenFred @zanetworker @mvladev @rfranzke
