### ISSUE TITLE
Extend vpn-seed with capabilities to open an ssh tunnel to the shoot network

### ISSUE THREAD

**Issue by stoyanr** [gardener/vpn#56]
**What would you like to be added**:

We would like to extend [vpn-seed](https://github.com/gardener/vpn/tree/master/seed) so that it opens an SSH tunnel to the shoot network automatically with certain command line options. These options should include:

* Whether to open a tunnel (by default false)
* The user and IP of the bastion host
* The network range
* The user's private key

**Why is this needed**:

Currently, if we use an OpenShift cluster that is not publicly exposed as a provider cluster with the [Kubevirt provider extension](https://github.com/gardener/gardener-extension-provider-kubevirt) in a test setup similar to [Development Setup](https://github.com/gardener/gardener-extension-provider-kubevirt/docs/dev-setup.md), Gardener reconciliation fails at the very end due to VPN connection between the seed and the shoot could not be established, because the IP address of the `vpn-shoot` LoadBalancer service is not a public one.

The only public IP address exposed is the one of the bastion host. Therefore, an SSH tunnel to the bastion host could be opened with [sshuttle](https://github.com/sshuttle/sshuttle) with a command similar to this one (assuming that ~/.ssh/id_rsa is a valid private key authorized by the bastion host):

```sh
sshuttle --dns -r <user>@<basion host IP> <network range> --python python3.8 -e "ssh -i ~/.ssh/id_rsa"
```

Such a tunnel is rather easy to setup and use locally. However, it's not easy to add `sshuttle` and the needed private keys to the `vpn-seed` container in the gardener `kube-apiserver` deployment in order to take advantage of it.

See also https://github.com/gardener/gardener-extension-provider-kubevirt/issues/35

/area networking
/kind enhancement
/priority normal

**Comment by zanetworker** [comment]
@stoyanr  Can you try enabling the `konnectivity-tunnel` feature with Openshift? Its experimental but should solve this issue.  

ref: https://github.com/gardener/gardener/blob/246443ffa2d9148ce8f6f46eda4396a1b3edfff5/docs/usage/reverse-tunnel.md

**Comment by stoyanr** [comment]
@zanetworker @rfranzke This seems to work quite well in this case, thanks! No need for any changes then, closing this ticket.
